# Generated by Django 5.1.4 on 2024-12-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretroom',
            name='not_standard',
            field=models.CharField(choices=[('N', 'Наличие галочки'), ('-', 'Отсутствие галочки')], default='N', max_length=5),
        ),
        migrations.AlterModelTable(
            name='secretroom',
            table='secret_room',
        ),
    ]
